# Generated by Django 5.2.5 on 2025-11-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile_background_color_profile_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='background_image',
        ),
        migrations.AddField(
            model_name='post',
            name='background_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='post',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_bg/'),
        ),
    ]
