# Generated by Django 5.2.5 on 2025-11-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_profile_background_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(blank=True, default='#ffffff', max_length=7)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='site_backgrounds/')),
            ],
            options={
                'verbose_name': 'Blog Setting',
                'verbose_name_plural': 'Blog Settings',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='background_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_backgrounds/'),
        ),
    ]
